version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    ignore:
      # The web ADB library should not be automatically updated because it introduces breaking changes too often
      - dependency-name: '@yume-chan/*'
