version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

# Uncomment this to re-enable automatic Node.js dependency updates
#  - package-ecosystem: npm
#    directory: /
#    schedule:
#      interval: weekly
#      day: monday
