name: Deploy static content to Pages

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  pages:
    uses: XaverianTeamRobotics/github-pages-deployment-action/.github/workflows/pages.yml@main
    with:
      website-base-path: webinstaller
      cloudflare-pages-project-name: xbhs-robotics-webinstaller
    secrets: inherit
